# Generated by Django 5.2 on 2025-09-10 01:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Antiprocrastinacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockedsite',
            unique_together={('usuario', 'url')},
        ),
    ]
