# Generated by Django 5.2 on 2025-09-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0008_usuariopersonalizado_urls_bloqueadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='modo_antiprocrastinacion',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='tiempo_activado',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='urls_bloqueadas',
        ),
    ]
